"""initial schema

Revision ID: 11e02838163f
Revises: 
Create Date: 2025-12-09 15:42:58.023441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e02838163f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False, comment='The name of the organization'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment='The slug of the organization (URL friendly identifier)'),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscription_tier_enum'), nullable=False, comment='The subscription tier of the organization'),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'TRIALING', 'CANCELLED', 'PAST_DUE', 'INCOMPLETE', name='subscription_status_enum'), nullable=False, comment='Current subscription status'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='Maximum number of users allowed for the organization'),
    sa.Column('max_datasets', sa.Integer(), nullable=False, comment='Maximum number of datasets allowed for the organization'),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False, comment='Maximum storage allowed for the organization in GB'),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True, comment='Stripe customer ID for billing'),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True, comment='Stripe subscription ID for billing'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='Flexible settings for the organization'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the organization is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Role name (e.g., Admin, Manager, Analyst, Viewer)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Description of the role and its permissions'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this role is assigned to new users by default'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Whether this is a system-defined role (cannot be deleted)'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='The organization this record belongs to'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Role table for multi-tenant data'
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (used for login)"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the user account is active'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Whether the user has superuser privileges (can access all organizations)'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Whether the user has verified their email address'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment="Timestamp of the user's last login"),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True, comment="OAuth provider (e.g., 'google', 'github')"),
    sa.Column('oauth_id', sa.String(length=255), nullable=True, comment="User's ID from the OAuth provider"),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='The organization this record belongs to'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User table for multi-tenant data'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
