"""Initial schema

Revision ID: 98815a29f5e4
Revises: ecda18feb576
Create Date: 2025-12-10 16:51:56.123291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98815a29f5e4'
down_revision = 'ecda18feb576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Permission unique identifier'),
    sa.Column('code', sa.String(length=100), nullable=False, comment="Permission code (e.g., 'data:import', 'org:manage')"),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name for the permission'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Description of what this permission allows'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Category: data, org, dashboard, user, billing, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stripe_monthly_price_id', sa.String(), nullable=True),
    sa.Column('stripe_yearly_price_id', sa.String(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_datasets', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=False),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_index(op.f('ix_subscription_plans_tier'), 'subscription_plans', ['tier'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_users', sa.Integer(), nullable=False),
    sa.Column('usage_datasets', sa.Integer(), nullable=False),
    sa.Column('usage_storage_gb', sa.Float(), nullable=False),
    sa.Column('usage_api_calls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('webhooks',
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization this webhook belongs to'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Descriptive name for this webhook'),
    sa.Column('url', sa.Text(), nullable=False, comment='Destination URL for webhook POSTs'),
    sa.Column('secret', sa.String(length=255), nullable=False, comment='Secret key for HMAC signature verification'),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of event types that trigger this webhook'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this webhook is active'),
    sa.Column('retry_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Retry configuration (max_attempts, backoff_strategy, timeout)'),
    sa.Column('last_triggered', sa.DateTime(), nullable=True, comment='Last time this webhook was triggered'),
    sa.Column('failure_count', sa.Integer(), nullable=False, comment='Consecutive failure count (reset on success)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Webhook table for multi-tenant event notifications'
    )
    op.create_index(op.f('ix_webhooks_is_active'), 'webhooks', ['is_active'], unique=False)
    op.create_index('ix_webhooks_org_active', 'webhooks', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_webhooks_organization_id'), 'webhooks', ['organization_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Dashboard name'),
    sa.Column('description', sa.Text(), nullable=True, comment="Optional description of the dashboard's purpose"),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Grid layout configuration for dashboard widgets'),
    sa.Column('widgets', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Array of widgets with their configurations'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Whether dashboard is shared with all organization members'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this dashboard'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='The organization this record belongs to'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Dashboard table for multi-tenant data'
    )
    op.create_index(op.f('ix_dashboards_created_by'), 'dashboards', ['created_by'], unique=False)
    op.create_index(op.f('ix_dashboards_is_public'), 'dashboards', ['is_public'], unique=False)
    op.create_index(op.f('ix_dashboards_name'), 'dashboards', ['name'], unique=False)
    op.create_index(op.f('ix_dashboards_organization_id'), 'dashboards', ['organization_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True, comment='True=grant, False=revoke'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('webhook_logs',
    sa.Column('webhook_id', sa.UUID(), nullable=False, comment='Webhook that was triggered'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Type of event that triggered this webhook'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Webhook payload (event data)'),
    sa.Column('response_status', sa.Integer(), nullable=True, comment='HTTP response status code (null if request failed)'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='HTTP response body (truncated to 10KB)'),
    sa.Column('attempt', sa.Integer(), nullable=False, comment='Delivery attempt number (1 for first attempt, 2+ for retries)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if delivery failed'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Request duration in milliseconds'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='The organization this record belongs to'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Webhook delivery log table'
    )
    op.create_index('ix_webhook_logs_created', 'webhook_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_logs_event_type'), 'webhook_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_organization_id'), 'webhook_logs', ['organization_id'], unique=False)
    op.create_index('ix_webhook_logs_status', 'webhook_logs', ['response_status'], unique=False)
    op.create_index('ix_webhook_logs_webhook_event', 'webhook_logs', ['webhook_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_webhook_logs_webhook_id'), 'webhook_logs', ['webhook_id'], unique=False)
    op.create_table('visualizations',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the visualization'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of what the visualization shows'),
    sa.Column('dataset_id', sa.UUID(), nullable=False, comment='Dataset this visualization is based on'),
    sa.Column('chart_type', sa.Enum('LINE', 'BAR', 'PIE', 'SCATTER', 'HEATMAP', 'TABLE', name='chart_type_enum'), nullable=False, comment='Type of chart to display (line, bar, pie, scatter, heatmap, table)'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Chart configuration including axes, grouping, aggregation, filters, and styling'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User who created this visualization'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='The organization this record belongs to'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Visualization table for multi-tenant data'
    )
    op.create_index(op.f('ix_visualizations_chart_type'), 'visualizations', ['chart_type'], unique=False)
    op.create_index(op.f('ix_visualizations_created_by'), 'visualizations', ['created_by'], unique=False)
    op.create_index(op.f('ix_visualizations_dataset_id'), 'visualizations', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_visualizations_name'), 'visualizations', ['name'], unique=False)
    op.create_index(op.f('ix_visualizations_organization_id'), 'visualizations', ['organization_id'], unique=False)
    op.create_table('dashboard_visualizations',
    sa.Column('dashboard_id', sa.UUID(), nullable=False, comment='Dashboard ID'),
    sa.Column('visualization_id', sa.UUID(), nullable=False, comment='Visualization ID'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the visualization was added to the dashboard'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visualization_id'], ['visualizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dashboard_id', 'visualization_id'),
    comment='Association table linking dashboards to their visualizations'
    )
    op.create_table('insights',
    sa.Column('dataset_id', sa.UUID(), nullable=False, comment='Dataset this insight is about'),
    sa.Column('insight_type', sa.Enum('TREND', 'ANOMALY', 'CORRELATION', 'SUMMARY', 'RECOMMENDATION', name='insight_type_enum'), nullable=False, comment='Type of insight (trend, anomaly, correlation, summary, recommendation)'),
    sa.Column('generated_by', sa.Enum('LLM', 'RULE_BASED', name='insight_generator_enum'), nullable=False, comment='Method used to generate this insight (LLM or rule-based)'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Brief title summarizing the insight'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the insight (often LLM-generated)'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score from 0.0 to 1.0'),
    sa.Column('data_support', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Data points, statistics, and evidence supporting this insight'),
    sa.Column('suggested_action', sa.Text(), nullable=True, comment='Actionable recommendation based on this insight'),
    sa.Column('visualization_id', sa.UUID(), nullable=True, comment='Optional visualization that illustrates this insight'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='The organization this record belongs to'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when this record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence_range'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visualization_id'], ['visualizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Insight table for multi-tenant data'
    )
    op.create_index(op.f('ix_insights_dataset_id'), 'insights', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_insights_generated_by'), 'insights', ['generated_by'], unique=False)
    op.create_index(op.f('ix_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_organization_id'), 'insights', ['organization_id'], unique=False)
    op.create_index(op.f('ix_insights_visualization_id'), 'insights', ['visualization_id'], unique=False)
    op.alter_column('datasets', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.alter_column('files', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.alter_column('organizations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.alter_column('records', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was soft-deleted (NULL if not deleted)'))
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.drop_column('roles', 'deleted_at')
    op.alter_column('records', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.alter_column('organizations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.alter_column('files', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.alter_column('datasets', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when this record was soft-deleted (NULL if not deleted)',
               existing_nullable=True)
    op.drop_index(op.f('ix_insights_visualization_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_organization_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_insight_type'), table_name='insights')
    op.drop_index(op.f('ix_insights_generated_by'), table_name='insights')
    op.drop_index(op.f('ix_insights_dataset_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_table('dashboard_visualizations')
    op.drop_index(op.f('ix_visualizations_organization_id'), table_name='visualizations')
    op.drop_index(op.f('ix_visualizations_name'), table_name='visualizations')
    op.drop_index(op.f('ix_visualizations_dataset_id'), table_name='visualizations')
    op.drop_index(op.f('ix_visualizations_created_by'), table_name='visualizations')
    op.drop_index(op.f('ix_visualizations_chart_type'), table_name='visualizations')
    op.drop_table('visualizations')
    op.drop_index(op.f('ix_webhook_logs_webhook_id'), table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_webhook_event', table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_status', table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_organization_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_event_type'), table_name='webhook_logs')
    op.drop_index('ix_webhook_logs_created', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_dashboards_organization_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_name'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_public'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_created_by'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_webhooks_organization_id'), table_name='webhooks')
    op.drop_index('ix_webhooks_org_active', table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_is_active'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_subscription_plans_tier'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
