"""
Pydantic schemas for API request/response validation.
"""

from app.schemas.visualization import (
    ChartConfig,
    VisualizationBase,
    VisualizationCreate,
    VisualizationUpdate,
    VisualizationInDB,
    VisualizationResponse,
    ChartSuggestion,
    ChartSuggestionRequest,
    ChartSuggestionsResponse,
    VisualizationListResponse,
    ChartDataExport,
)

from app.schemas.dashboard import (
    DashboardWidget,
    DashboardLayout,
    DashboardBase,
    DashboardCreate,
    DashboardUpdate,
    DashboardInDB,
    PopulatedWidget,
    DashboardResponse,
    AddWidgetRequest,
    UpdateWidgetRequest,
    RemoveWidgetRequest,
    AddVisualizationRequest,
    DashboardListResponse,
    DashboardExport,
    DashboardTemplate,
    DashboardShareSettings,
)

from app.schemas.insight import (
    InsightBase,
    InsightCreate,
    InsightUpdate,
    InsightInDB,
    InsightSummary,
    InsightResponse,
    InsightListResponse,
    GenerateInsightsRequest,
    GenerateInsightsResponse,
    InsightsByTypeResponse,
    TrendDataSupport,
    AnomalyDataSupport,
    CorrelationDataSupport,
    SummaryDataSupport,
    RecommendationDataSupport,
    InsightQuestionRequest,
    InsightQuestionResponse,
    ExplainInsightRequest,
    ExplainInsightResponse,
)

from app.schemas.webhook import (
    WebhookBase,
    WebhookCreate,
    WebhookUpdate,
    WebhookResponse,
    WebhookListResponse,
    WebhookLogResponse,
    WebhookLogListResponse,
    WebhookWithLogsResponse,
    WebhookTestRequest,
    WebhookTestResponse,
    InboundWebhookResponse,
)

__all__ = [
    # Visualization schemas
    "ChartConfig",
    "VisualizationBase",
    "VisualizationCreate",
    "VisualizationUpdate",
    "VisualizationInDB",
    "VisualizationResponse",
    "ChartSuggestion",
    "ChartSuggestionRequest",
    "ChartSuggestionsResponse",
    "VisualizationListResponse",
    "ChartDataExport",
    # Dashboard schemas
    "DashboardWidget",
    "DashboardLayout",
    "DashboardBase",
    "DashboardCreate",
    "DashboardUpdate",
    "DashboardInDB",
    "PopulatedWidget",
    "DashboardResponse",
    "AddWidgetRequest",
    "UpdateWidgetRequest",
    "RemoveWidgetRequest",
    "AddVisualizationRequest",
    "DashboardListResponse",
    "DashboardExport",
    "DashboardTemplate",
    "DashboardShareSettings",
    # Insight schemas
    "InsightBase",
    "InsightCreate",
    "InsightUpdate",
    "InsightInDB",
    "InsightSummary",
    "InsightResponse",
    "InsightListResponse",
    "GenerateInsightsRequest",
    "GenerateInsightsResponse",
    "InsightsByTypeResponse",
    "TrendDataSupport",
    "AnomalyDataSupport",
    "CorrelationDataSupport",
    "SummaryDataSupport",
    "RecommendationDataSupport",
    "InsightQuestionRequest",
    "InsightQuestionResponse",
    "ExplainInsightRequest",
    "ExplainInsightResponse",
    # Webhook schemas
    "WebhookBase",
    "WebhookCreate",
    "WebhookUpdate",
    "WebhookResponse",
    "WebhookListResponse",
    "WebhookLogResponse",
    "WebhookLogListResponse",
    "WebhookWithLogsResponse",
    "WebhookTestRequest",
    "WebhookTestResponse",
    "InboundWebhookResponse",
]
